### ISSUE TITLE
Quick Switch Project Dialog is scrambled.

### ISSUE THREAD

**Issue by valeryan** [dmnplb/curiosity#1]
Environment: Sublime Text 3 build 3084, OSX

When selecting Quick Switch Projects from the Projects menu in sublime or using the keys 'ctrl+super+p' the dialog has a scrambled display. This is only occurring when this theme is active. all other menus and dialogs appear to be unaffected. I use multiple monitors and the scrambling happens on the external monitors and not on the laptops retina display unless I resize the window. 

![screen shot 2015-04-09 at 3 28 49 pm](https://cloud.githubusercontent.com/assets/1508761/7076409/d18d6980-dece-11e4-9c27-25659bb9809d.png)

**Comment by dmnplb** [comment]
@valeryan Thanks for your detailed feedback. I don't use this feature regularly, so I didn't notice this glitch. I'll fix it as soon as possible.

**Comment by dmnplb** [comment]
@valeryan Transparency caused this glitch. The only way to remove it is to turn off transparency in “Quick Panel” and “Go to…” panel. You can disable transparency via the new setting, released for this specific problem: `“curiosity_notransparency”: true`

Let me know if this setting resolve your issue.

**Comment by valeryan** [comment]
That does indeed fix the problem for me. Thanks for the quick response. Now I can fully enjoy your awesome theme.

**Comment by dmnplb** [comment]
@valeryan Thank you, Samuel. I'm glad you're enjoying it :)
